name: CI/CD

permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn build

  sync-main-branch:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    name: Deploy to Mirror Repository

    steps:
      - name: Checkout code from main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push main branch to the mirror repo
        env:
          GIT_PAT: ${{ secrets.MIRROR_REPO_PAT }}
        run: |
          echo "Setting up Git identity..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "Attempting git push directly with URL and high verbosity..."
          if [ -z "${GIT_PAT}" ]; then
            echo "Error: GIT_PAT environment variable is not set!"
            exit 1
          fi

          # Enable verbose Git logging
          export GIT_CURL_VERBOSE=1
          export GIT_TRACE=1
          
          # Construct the URL (ensure no trailing slash)
          TARGET_REPO_URL="https://x-access-token:${GIT_PAT}@github.com/MdRasulov/pms-admin-dashboard.git"
          
          echo "Pushing to target repository: github.com/MdRasulov/pms-admin-dashboard.git" # Log target without token
          
          # Push directly using the full URL
          # Syntax: git push <repository> <local_ref>:<remote_ref> --force
          git push "${TARGET_REPO_URL}" main:main --force
          
          echo "Git push command executed."
